# FUNDING.yml
# This file tells GitHub where to send sponsorship traffic

patreon: RelunSec     
open_collective: relunsec
ko_fi: relunsec
custom: ["bitcoin:bc1qeqct6n3kncynvdjls4yv9r6patpfcufp24gvk3"]
