# FUNDING.yml
# This file tells GitHub where to send sponsorship traffic

patreon: RelunSec     
open_collective: relunsec
ko_fi: relunsec
custom: lnurlp://mainnet.demo.btcpayserver.org/BTC/UILNURL/2EYDhcF83tdF1Uadtr269Kn88Mxm1P4DpCSACspNasst/pay?currency=USD
