name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: none

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write # Only give it exactly what it needs to label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # Pinned SHA
        with:
          repo-token: "${{ secrets.LABELER_TOKEN }}"
